- name: Block Demo
  hosts: servera*
  gather_facts: true
  become: false
  vars_files:
    - vars/outside_vars.yml
  tasks:
    - name: Store Facts Outside Block
      ansible.builtin.copy:
        dest: /tmp/{{ inventory_hostname }}
        content: |
          Magic Variable  = {{ inventory_hostname }}
          Arch3           = {{ ansible_facts['architecture'] }}
          Date            = {{ ansible_facts['date_time']['date'] }}
          Time            = {{ ansible_facts['date_time']['time'] }}
          IP Address      = {{ ansible_facts['default_ipv4']['address'] }}

    - name: Block for Web Server Tasks
      become: true
      when:
        - ansible_facts['kernel'] > "5.10"
        - ansible_facts['distribution'] in  os_list
      block:
        - name: Install Web Server
          ansible.builtin.dnf:
            name: httpd
            state: present

        - name: Deploy Web App
          ansible.builtin.copy:
            dest: /var/www/html/index.html
            content: "Hello Web App"
            mode: "0644"

        - name: Start Web Service
          ansible.builtin.service:
            name: httpd
            state: started
      rescue:
        - name: Restore Last Known Good Config
          ansible.builtin.debug:
            msg: "MayDay Mayday UNDO Everything"

        - name: Undeploy Web Application
          ansible.builtin.shell:
            cmd: rm -rf /var/www/html/*

        - name: Uninstall Web Server
          ansible.builtin.dnf:
            name: httpd
            state: absent
            autoremove: true
      always:
        - name: Inform Stakeholders
          ansible.builtin.debug:
            msg: "Email Sent"
          # community.general.mail:
    - name: Task Outside Block 2
      ansible.builtin.debug:
        msg: "This Task is Outside Block"
      # community.general.mail:
