- name: Facts Demo
  hosts: servera*
  gather_facts: false
  tasks:
    - name: Change place for Custom Facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "min"
          - "network"
          - "hardware"
        fact_path: /etc/ansible/facts.d

    - name: Store Facts
      ansible.builtin.debug:
        msg: >
          Magic Variable  = {{ inventory_hostname }}
          Arch1           = {{ ansible_architecture }}
          Arch2           = {{ ansible_facts.architecture }}
          Arch3           = {{ ansible_facts['architecture'] }}
          Date            = {{ ansible_facts['date_time']['date'] }}
          Time            = {{ ansible_facts['date_time']['time'] }}
          IP Address      = {{ ansible_facts['default_ipv4']['address'] }}
          Mac Address     = {{ ansible_default_ipv4.macaddress }}
      
    - name: Setup Custom Facts only for this run
      ansible.builtin.set_fact:
        laptop: "Level-19 Laptop belong to  {{ ansible_facts.ansible_local.company.user.emp_name }} whose location is {{ ansible_facts.ansible_local.company.dept.dept_location }} "

    - name: Store Facts
      ansible.builtin.copy:
        dest: /tmp/{{ inventory_hostname }}
        content: |-
          Magic Variable  = {{ inventory_hostname }}
          Arch1           = {{ ansible_architecture }}
          Arch2           = {{ ansible_facts.architecture }}
          Arch3           = {{ ansible_facts['architecture'] }}
          Date            = {{ ansible_facts['date_time']['date'] }}
          Time            = {{ ansible_facts['date_time']['time'] }}
          IP Address      = {{ ansible_facts['default_ipv4']['address'] }}
          Mac Address     = {{ ansible_default_ipv4.macaddress }}
          VDA Size        = {{ ansible_facts['devices']['vda']['size'] }}
          OS Type         = {{ ansible_facts['distribution'] }}
          OS Version      = {{ ansible_facts['distribution_version'] }}
          FQDN            = {{ ansible_facts['fqdn'] }}
          Hostname        = {{ ansible_hostname }}
          Kernel          = {{ ansible_facts.kernel }}
          Total Memory    = {{ ansible_facts['memory_mb']['real']['total'] }}
          Free Memory     = {{ ansible_facts['memory_mb']['real']['free'] }}
          Python Ver      = {{ ansible_facts['python_version'] }}
          User Name       = {{ ansible_facts.ansible_local.company.user.emp_name}}
          Dept Manager    = {{ ansible_facts.ansible_local.company.dept.dept_manager }}
          CUSTOM          = {{ laptop }}

    - name: Create a user
      ansible.builtin.user:
        name: sangmin
        shell: /bin/bash
        state: present
        uid: 2000
      when: ansible_facts['kernel'] > "5.15" 

