- name: Setup Oracle Task 1
  ansible.builtin.debug:
    msg: "Oracle Task 1 Completed"

- name: Setup Oracle Task 2
  ansible.builtin.debug:
    msg: "Oracle Task 2 Completed"

- name: Setup Oracle Task 3
  ansible.builtin.debug:
    msg: "Oracle Task 3 Completed"

- name: Setup Oracle Task 4
  ansible.builtin.debug:
    msg: "Oracle Task 4 Completed"
