---
# handlers file for security_server

- name: Security Package Installed
  ansible.builtin.debug:
    msg: "Package {{ security_server_package }} Installed Success"
     
- name: Start Security Service
  ansible.builtin.service:
    name: "{{ security_server_service }}"
    state: restarted

- name: Web Port Opened
  ansible.builtin.debug:
    msg: "Web Port {{ security_server_port }} Opened Success"

